version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.1.1
    ports:
      - '9200:9200'
    expose:
      - 9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  dynamodb:
    build: ./dynamodb
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    ports:
      - '8000:8000'
    command: -jar DynamoDBLocal.jar -dbPath ./data -sharedDb
volumes:
  es-data:
    driver: local
  dynamodb-data:
