version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.1.1
    ports:
      - '9200:9200'
    expose:
      - 9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  dynamodb:
    image: amazon/dynamodb-local:1.12.0
    ports:
      - '8000:8000'
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
volumes:
  es-data:
    driver: local
