AWSTemplateFormatVersion: '2010-09-09'
Description: Elasticsearch Sample

Parameters:
  NamePrefix:
    Type: String
    Default: aws-elasticsearch-sample

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 'cloudformation:*'
                - 'es:*'
              Resource: '*'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: operate Elasticsearch
      FunctionName: ElasticsearchSampleLambdaFunction
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs10.x
      Code: src/dist/
      Timeout: 30
      MemorySize: 256

Outputs:
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${NamePrefix}-lambda-role-arn'
