AWSTemplateFormatVersion: '2010-09-09'
Description: Elasticsearch Sample Setup Template

Parameters:
  NamePrefix:
    Type: String
  BucketName:
    Type: String

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 'cloudformation:*'
                - 'es:*'
                - 'dynamodb:DescribeStream'
                - 'dynamodb:GetShardIterator'
                - 'dynamodb:GetRecords'
                - 'dynamodb:ListStreams'
                - 'dynamodb:PutItem'
                - 'logs:CreateLogGruop'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'

Outputs:
  LambdaExecutionRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: !Sub '${NamePrefix}-lambda-role-arn'
