AWSTemplateFormatVersion: '2010-09-09'
Description: Elasticsearch Sample Setup Template

Parameters:
  BucketName:
    Type: String

Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
